import Header from '../components/Header'
import Head from 'next/head'
import LandingSection from '../components/LandingSection'
import PortfolioSection from '../components/PortfolioSection'
import SkillsSection from '../components/SkillsSection'
import ContactSection from '../components/ContactSection'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className=' text-white'>

        <LandingSection />


        <PortfolioSection />

        <SkillsSection />


        <ContactSection />



      </main>

    </>
  )
}
